version: '3.1'

services:
  redis:
    image: redis:latest
    container_name: bloom-filter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
    env_file:
      - "./env/redis.env"