version: '3.1'

services:
#   Load balancer service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bloom-filter-backend-1
      - bloom-filter-backend-2
      - bloom-filter-backend-3

  redis:
    image: redis:latest
    container_name: bloom-filter-redis
    command:
      - bash
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
    env_file:
      - "./env/redis.env"

  bloom-filter-backend-1:
    build:
      context: ../../
      dockerfile: infra/docker/backend/dockerfile
    container_name: bloom-filter-backend-1
    ports:
      - "8081:8081"
    environment:
      env: DOCKER
      SPRING_PORT: 8081
    env_file:
      - "./env/redis.env"
    depends_on:
      - redis

  bloom-filter-backend-2:
    build:
      context: ../../
      dockerfile: infra/docker/backend/dockerfile
    container_name: bloom-filter-backend-2
    ports:
      - "8082:8082"
    environment:
      env: DOCKER
      SPRING_PORT: 8082
    env_file:
      - "./env/redis.env"
    depends_on:
      - redis

  bloom-filter-backend-3:
    build:
      context: ../../
      dockerfile: infra/docker/backend/dockerfile
    container_name: bloom-filter-backend-3
    ports:
      - "8083:8083"
    environment:
      env: DOCKER
      SPRING_PORT: 8083
    env_file:
      - "./env/redis.env"
    depends_on:
      - redis

volumes:
  redis: