FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app

COPY ../../../pom.xml .

RUN mvn dependency:go-offline -B

COPY ../../../src ./src

RUN mvn clean package -DskipTests

FROM openjdk:21

WORKDIR /app

COPY --from=build /app/target/Bloom-filter-1.0-SNAPSHOT.jar ./Bloom-filter-1.0-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "Bloom-filter-1.0-SNAPSHOT.jar"]